steps:
- name: 'gcr.io/cloud-builders/gcloud'
  
  script: |
    existing_tags=$(gcloud container images list --repository=gcr.io/elite-totem-410916 --filter="name:base_image" --format=json")
    if [[ "$existing_tags" == "[]" ]]; then
      printf "tag does not exist"
    else
      printf "tag exists"
    fi

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/elite-totem-410916/trainer:latest', '.', '-f', 'dockerfiles/train_model.dockerfile']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/elite-totem-410916/trainer:latest']



