steps:
- name: 'gcr.io/cloud-builders/gcloud'
  
  script: |
    #!/bin/bash

    existing_tags=$(gcloud container images list --repository=gcr.io/elite-totem-410916 --filter="name:base_image" --format=json)


    if [[ $(git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep requirements.txt) || "$existing_tags" == "[]" ]]; then
      gcloud builds submit --config cloudbuild.yaml --substitutions=_IMAGE_EXISTS="$IMAGE_EXISTS"
    else
      echo "No changes in requirements.txt or Docker image already exists. Skipping build."
    fi

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/elite-totem-410916/trainer:latest', '.', '-f', 'dockerfiles/train_model.dockerfile']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/elite-totem-410916/trainer:latest']



