steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['cloud_yaml/bash_script.sh']

 
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/elite-totem-410916/trainer:latest', '.', '-f', 'dockerfiles/train_model.dockerfile']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/elite-totem-410916/trainer:latest']



