steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ $(git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep requirements.txt) ]]; then
      gcloud builds submit --config cloud_yaml/cloudbuild_base_image.yaml .
    else
      echo "No changes in requirements.txt. Using latest base image."
    fi

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/elite-totem-410916/predicter:latest', '.', '-f', 'dockerfiles/predict_model.dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/elite-totem-410916/predicter:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'predicter'
  - '--image'
  - 'gcr.io/elite-totem-410916/predicter:latest'
  - '--region'
  - 'europe-west1'
  - '--memory'
  -  '2Gi'


