steps:
- name: 'bash'
  script: |
    IMAGE_EXISTS=$(gcloud container images describe gcr.io/elite-totem-410916/base_image:latest --format="value(image_summary.image)%' ' 2>/dev/null")
    if [[ -z "$IMAGE_EXISTS" ]]; then
      gcloud builds submit --config cloud_yaml/cloudbuild_base_image.yaml .
    else
      echo "Base image already exists. Skipping build."
    fi
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/elite-totem-410916/predicter:latest', '.', '-f', 'dockerfiles/predict_model.dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/elite-totem-410916/predicter:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'predicter'
  - '--image'
  - 'gcr.io/elite-totem-410916/predicter:latest'
  - '--region'
  - 'europe-west1'
  - '--memory'
  -  '2Gi'


