steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/elite-totem-410916/reports:latest', '.', '-f', 'dockerfiles/reports.dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/elite-totem-410916/reports:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'reports'
  - '--image'
  - 'gcr.io/elite-totem-410916/reports:latest'
  - '--region'
  - 'europe-west1'
  - '--memory'
  -  '4Gi'


